//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assignments
    {
        public int assignmentId { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public System.DateTime subDateTime { get; set; }
        public int oralMark { get; set; }
        public int totalMark { get; set; }
        public int courseId { get; set; }
    
        public virtual Courses Courses { get; set; }
    }
}
